# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sumCpp <- function(x) {
    .Call(`_SundusGenome1_sumCpp`, x)
}

add_vecs <- function(a, b) {
    .Call(`_SundusGenome1_add_vecs`, a, b)
}

subset_vec <- function(a, b) {
    .Call(`_SundusGenome1_subset_vec`, a, b)
}

